### ISSUE TITLE
Scala.js in v4.0.0

### ISSUE THREAD

**Issue by sief** [dwickern/scala-nameof#24]
Thanks for this great library.
I noticed that release v4.0.0 doesn't support Scala.js anymore. Is there a specific reason for this?

**Comment by dwickern** [comment]
I had a hard time to get Scala 3 working since the tooling for Scala 3 macros was quite bad (at least how it was ~2 years ago). Scala.js was making it more complicated. A PR to add it back would be most welcome.

Honestly I am not very familiar with Scala.js. What happens when you use the dependency this way in a Scala.js project?
```sbt
libraryDependencies += "com.github.dwickern" %% "scala-nameof" % "4.0.0" % "provided"
```

**Comment by sief** [comment]
it doesn't compile:

`object github is not a member of package com import com.github.dwickern.macros.NameOf.nameOf`

**Comment by sief** [comment]
anyway, it's good to know that it's not generally impossible. I'll try to find some time for a PR.
